modLoader="javafml" 
loaderVersion="[47,)"  # Forge 47.x.x for Minecraft 1.20.1
license="MIT"
issueTrackerURL="https://github.com/kenai/recipe_extractor/issues"

[[mods]]
modId="recipe_extractor_mod"
version="1.0"
displayName="Recipe Extractor Mod"
description="Extract recipes from Minecraft."
authors="Kenai"
credits="Forge team"
logoFile="assets/recipe_extractor_mod/textures/logo.png"

[[dependencies.recipe_extractor_mod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.recipe_extractor_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"